version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python populate_app.py && python manage.py runserver"
    container_name: bikezon
    volumes:
      - .:/bikezon
    ports:
      - "8000:8000"