# Generated by Django 3.0.3 on 2020-03-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200304_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
