# Generated by Django 3.0.3 on 2020-03-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='slug',
            field=models.SlugField(),
        ),
    ]
