# Generated by Django 3.0.3 on 2020-03-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_followergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followergroup',
            name='group_followers',
            field=models.ManyToManyField(related_name='follower', to='app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='followergroup',
            name='group_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='app.UserProfile'),
        ),
    ]
