# Generated by Django 3.0.3 on 2020-03-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200305_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_id',
            new_name='id',
        ),
    ]
