# Generated by Django 3.0.3 on 2020-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200313_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='item',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
