# Generated by Django 3.0.3 on 2020-03-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200305_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
