# Generated by Django 3.0.3 on 2020-03-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200318_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='media/profile_images'),
        ),
    ]
